# Spring Boot Application Name
spring.application.name=FurEver

# FurEver Connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.jwclsknvjsuptkttkzkr
spring.datasource.password=Furever#0910
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Supabase Project URL
supabase.url=https://jwclsknvjsuptkttkzkr.supabase.co
supabase.api-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3Y2xza252anN1cHRrdHRremtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NzAyOTksImV4cCI6MjA4NjI0NjI5OX0.2_jcRU2Pamne4Rk1HAx8h4GP8E6n2Go7UH88Dv65sbc

# JWT Configuration (Keep your secret strong!)
furever.jwt.secret=SOL29Ro6ucowN/8B9GvEK/7Y26LZ1VjJvlrD21ZyrkN6bbw+0XRoO8LtwRHQkPxsAr2g++rPdJU6AFu/TlGFHw==
furever.jwt.expiration=36000